### ISSUE TITLE
No Timer/Reactor per thread: Uses CurrentThread Runtime with ParkThread Park impl

### ISSUE THREAD

**Issue by sdroege** [jonhoo/tokio-io-pool#1]
Currently it looks like tokio-io-pool uses the default `Park` of `CurrentThread`, which is `ParkThread`. That one is basically a condition variable and nothing else.

That means, from what I understand, that a global `Reactor` (and `Timer`) instance is created, and not one per thread.

AFAIU to have one reactor per runtime, something like the following would be needed

```rust
    let reactor = reactor::Reactor::new().unwrap();
    let handle = reactor.handle();
    let mut enter = ::tokio_executor::enter().unwrap();
    let timer = timer::Timer::new(reactor);
    let timer_handle = timer.handle();
    let mut current_thread = tokio_current_thread::CurrentThread::new_with_park(timer);

    ::tokio_reactor::with_default(&handle, &mut enter, |mut enter| {
        ::tokio_timer::with_default(&timer_handle, &mut enter, |enter| {
            current_thread.run();
        }
    }
```

**Comment by sdroege** [comment]
I'm not sure why this was decided for `CurrentThread` though, maybe the above should be the default behaviour instead? CC @carllerche

**Comment by sdroege** [comment]
See also https://github.com/tokio-rs/tokio/blob/master/examples/manual-runtime.rs

**Comment by sdroege** [comment]
Ah nevermind, should've had my coffee first! Mixed up the `CurrentThread` runtime and executor.

**Comment by jonhoo** [comment]
You are right to observe that there are some shortcomings here though, in particular when it comes to `block_on`. There's some discussion of that starting at https://gitter.im/tokio-rs/dev?at=5b47934fbd14e65d2f62b05b if you're curious.
